eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
register-with-eureka: true # By default, this is true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
zipkin:
  tracing:
    endpoint:https://localhost:9411



spring:
  zipkin:
    base-url: http://localhost:9411
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - http://localhost:29092
          bindings:
            springCloudBusOutput:
              destination: springCloudBusTopic
            springCloudBusInput:
              destination: springCloudBusTopic
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
  kafka:
    bootstrap-servers:
      - http://localhost:29092
server:
  port: 8082

example:
  message: "44444 This is a test message from user-service"

rest-api-2:
  url: http://localhost:8081

