server:
  port: 8222
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - http://localhost:29092
        bindings:
          springCloudBusOutput:
            destination: springCloudBusTopic
          springCloudBusInput:
            destination: springCloudBusTopic
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: "discovery-service"
          uri: "http://localhost:8761"
          predicates:
            - Path=/discovery/**
            - Method=GET
          filters:
            - RewritePath=/discovery(?<segment>.*), /${segment}
        - id: "user-service"
          uri: "http://localhost:8081"
          predicates:
            - Path=/users/**
            - Method=GET
          filters:
            - RewritePath=/users(?<segment>.*), /${segment}
  kafka:
    bootstrap-servers:
      - http://localhost:29092
management:
  endpoints:
    web:
      exposure:
        include: "*"
