server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: "discovery-service"
#          uri: "http://localhost:8761"
#          predicates:
#            - Path=/discovery/**
#          filters:
#            - RewritePath=/discovery/(?<segment>.*), /${segment}
