eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
register-with-eureka: true # By default, this is true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  stream:
    kafka:
      binder:
        brokers:
          - http://localhost:29092
  kafka:
    bootstrap-servers: http://localhost:29092


  bus:
    trace:
      enabled: true
    refresh:
      enabled: true
    env:
      enabled: true

server:
  port: 8081
