eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
register-with-eureka: true # By default, this is true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0

spring:
  sleuth:
    propagation:
      type: w3c,b3
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - http://localhost:29092
          bindings:
            springCloudBusOutput:
              destination: springCloudBusTopic
            springCloudBusInput:
              destination: springCloudBusTopic
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
  kafka:
    bootstrap-servers:
      - http://localhost:29092
server:
  port: 8081

example:
  message: "44444 This is a test message from user-service"